import { env } from './env'

export const X402_CONFIG = {
  USDC_DEVNET_MINT: env.NEXT_PUBLIC_USDC_DEVNET_MINT,
  TREASURY_ADDRESS: env.NEXT_PUBLIC_TREASURY_ADDRESS,
  REQUIRED_AMOUNT: Math.floor(
    env.NEXT_PUBLIC_PAYMENT_AMOUNT_USD * Math.pow(10, env.NEXT_PUBLIC_USDC_DECIMALS),
  ).toString(),
  FACILITATOR_BASE_URL: env.NEXT_PUBLIC_FACILITATOR_URL,
  COOKIE_NAME: env.NEXT_PUBLIC_COOKIE_NAME,
  COOKIE_MAX_AGE: env.NEXT_PUBLIC_COOKIE_MAX_AGE,
  PAYMENT_SCHEME: env.NEXT_PUBLIC_PAYMENT_SCHEME,
  NETWORK: env.NEXT_PUBLIC_NETWORK,
  PAYMENT_DESCRIPTION: env.NEXT_PUBLIC_PAYMENT_DESCRIPTION,
  PAYMENT_TIMEOUT_SECONDS: env.NEXT_PUBLIC_PAYMENT_TIMEOUT_SECONDS,
} as const
